### PR TITLE
Fix bugs with spaces 

### PR DESCRIPTION
**Pull request by msnyder-msft**
Attempts at fixing #3 & #4 . They seem to be working now. All the strings come out without the prefixed space and the splitting is now working just fine.

### CODE REVIEW

**Comment by while1618** [comment]
Hi @msnyder-msft thanks for the contribution, this issue was pointed out in one previous issue, but I didn't have time to fix it. It's not only related to Azure API, but all of them. I'll use your approach and try to fix(probably during the weekend) all the APIs. It would be great if you can send me part of your en.json file in which the problem occurred, so I can test on it.

**Comment by msnyder-msft** [comment]
Sure thing! I actually found that it was more reliable to send each string separately to the API to get translated rather than as a single document. That solved all the problems. Though it is definitely less performant and potentially more expensive depending on how the costing works. You can find those refactors in the Azure API on my fork if you're interested.

Here's a snippet of my en file if you still need it.

{
    "preview": "Preview",
    "loading": "Loading...",
    "label": "Label",
    "min": "Min",
    "max": "Max",
    "noData": "No data",
    "error": "Error fetching data",
    "unsupportedFileType": "Unsupported file type",
    "selectProperties": "Select properties",
    "empty": "Empty",
    "theme": "Theme",
    "hierarchy": "Hierarchy",
    "displayName": "Display name",
    "realTimeStatus": "Real-time status",
    "emptyCompositeCard": "Empty composite card",
    "compositeCardWithErrors": "Composite card with error boundaries",
    "showMore": "Show more",
    "unauthorizedAccessErrorTitle": "Access Restricted",
    "unauthorizedAccessErrorMessage": "You do not have access to this blob. Request Reader access or try a different blob.",
    "nonExistentBlobErrorTitle": "Blob Error",
    "nonExistentBlobErrorMessage": "Blob does not exist.",
    "readerAccessOnlyErrorMessage": "You have read access for this blob. This means that you will be able to view the models, but will not be able to create or configure any scenes, elements, or behaviors.",
    "tryAgain": "Try Again",
    "learnMore": "Learn More",
    "DataFetchFailed": "Data Fetch Failed",
    "more": "More",
    "search": "Search",
    "noSearchResults": "No twins found for entered search term (search is case sensitive).",
    "model": "Model",
    "noTwins": "No twins",
    "noModels": "No models",
    "true": "True"
}




[http://mysignature/Templates/Logos/L_Microsoft.png]



Mitch Snyder (He/Him)
Senior Software Engineer

Azure IOT – Azure Digital Twins UX

Mobile: +1 (402) 440-2414

***@***.*** ***@***.***>
Working hours: 9am-5pm PST



[http://mysignature/Templates/Social/SI_facebook.png]<https://www.facebook.com/Mitch726>    [http://mysignature/Templates/Social/SI_linkedin.png] <https://www.linkedin.com/in/mitch-snyder/>


________________________________

**Comment by while1618** [comment]
Thanks for the input example. I'll try to fix the problem as soon as possible, I'm expecting to have some free time in a day or two.

Regarding your suggestion to send a request for every key-value pair, I don't want to do that because of performance and price cost. Some APIs base their prices on how many request you send, and they also have request per minute block, if you are not paying for the most expensive package. The other problem is that if you have a large file, that can cause a large amount of API calls(e.g. 1000), and that will slow down a library drastically.

Anyway, thanks for your feedback, I'll let you know when the bug is resolved.

**Comment by while1618** [comment]
Hi @msnyder-msft, this problem should be fixed in v1.1.10. I have changed the delimiter, and that weird space is no longer a problem. The new delimiter is ' {|} ', and as I can tell, all the API providers will just skip every word inside curly braces, and it won't be translated, because of that, no weird space will be added in some random scenarios. You can check the new version, and please let me know if you face some problems. You can just open a new issue.

**Pull request closed without merging**
